version: 2
updates:
  - package-ecosystem: npm
    directory: "/"
    schedule:
      interval: daily
      time: "04:00"
      timezone: Europe/London
    open-pull-requests-limit: 5
    commit-message:
      prefix: chore
      include: scope
    ignore:
      - dependency-name: "@semantic-release/*"
      - dependency-name: "semantic-release"
      - dependency-name: "@types/node"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    commit-message:
      prefix: chore
      include: scope
